MML.hitPositions = {
  humanoid: {
    1: {name: "Top of Head", bodyPart: "Head"},
    2: {name: "Face", bodyPart: "Head"},
    3: {name: "Rear of Head", bodyPart: "Head"},
    4: {name: "Right Side of Head", bodyPart: "Head"},
    5: {name: "Left Side of Head", bodyPart: "Head"},
    6: {name: "Neck, Throat", bodyPart: "Head"},
    7: {name: "Rear of Neck", bodyPart: "Head"},
    8: {name: "Right Shoulder", bodyPart: "Right Arm"},
    9: {name: "Right Upper Chest", bodyPart: "Chest"},
    10: {name: "Right Upper Back", bodyPart: "Chest"},
    11: {name: "Left Upper Chest", bodyPart: "Chest"},
    12: {name: "Left Upper Back", bodyPart: "Chest"},
    13: {name: "Left Shoulder", bodyPart: "Left Arm"},
    14: {name: "Right Upper Arm", bodyPart: "Right Arm"},
    15: {name: "Right Lower Chest", bodyPart: "Chest"},
    16: {name: "Right Mid Back", bodyPart: "Chest"},
    17: {name: "Left Lower Chest", bodyPart: "Chest"},
    18: {name: "Left Mid Back", bodyPart: "Chest"},
    19: {name: "Left Upper Arm", bodyPart: "Left Arm"},
    20: {name: "Right Elbow", bodyPart: "Right Arm"},
    21: {name: "Right Abdomen", bodyPart: "Abdomen"},
    22: {name: "Right Lower Back", bodyPart: "Abdomen"},
    23: {name: "Left Abdomen", bodyPart: "Abdomen"},
    24: {name: "Left Lower Back", bodyPart: "Abdomen"},
    25: {name: "Left Elbow", bodyPart: "Left Arm"},
    26: {name: "Right Forearm", bodyPart: "Right Arm"},
    27: {name: "Right Hip", bodyPart: "Abdomen"},
    28: {name: "Right Buttock", bodyPart: "Abdomen"},
    29: {name: "Left Hip", bodyPart: "Abdomen"},
    30: {name: "Left Buttock", bodyPart: "Abdomen"},
    31: {name: "Left Forearm", bodyPart: "Left Arm"},
    32: {name: "Right Hand/Wrist", bodyPart: "Right Arm"},
    33: {name: "Groin", bodyPart: "Abdomen"},
    34: {name: "Left Hand/Wrist", bodyPart: "Left Arm"},
    35: {name: "Right Upper Thigh", bodyPart: "Right Leg"},
    36: {name: "Left Upper Thigh", bodyPart: "Left Leg"},
    37: {name: "Right Lower Thigh", bodyPart: "Right Leg"},
    38: {name: "Left Lower Thigh", bodyPart: "Left Leg"},
    39: {name: "Right Knee", bodyPart: "Right Leg"},
    40: {name: "Left Knee", bodyPart: "Left Leg"},
    41: {name: "Right Upper Shin", bodyPart: "Right Leg"},
    42: {name: "Left Upper Shin", bodyPart: "Left Leg"},
    43: {name: "Right Lower Shin", bodyPart: "Right Leg"},
    44: {name: "Left Lower Shin", bodyPart: "Left Leg"},
    45: {name: "Right Foot/Ankle", bodyPart: "Right Leg"},
    46: {name: "Left Foot/Ankle", bodyPart: "Left Leg"}
  }
};
