const melee_weapon_list = {
  "Ballock Dagger": {
    "name": "Ballock Dagger",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "7(-1c)",
    "thrust": "6(+1p)",
    "defense_guard": "8(1)",
    "special": "Fluid Thrusts, Light Blade",
    "weight": "0",
    "cost": "5 cp"
  },
  "Baselard": {
    "name": "Baselard",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "S",
    "swing": "6(+0c)",
    "thrust": "6(+0p)",
    "defense_guard": "7(1)",
    "special": "Fluid Thrusts",
    "weight": "0",
    "cost": "2 sp"
  },
  "Bowie Knife/ Pishkan Toothpick": {
    "name": "Bowie Knife/ Pishkan Toothpick",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "S",
    "swing": "6(+0c)",
    "thrust": "6(+1p)",
    "defense_guard": "8(1)",
    "special": "-",
    "weight": "0",
    "cost": "10 cp"
  },
  "Cinquedea": {
    "name": "Cinquedea",
    "weapon_type": "Dagger, Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "6(+0c)",
    "thrust": "7(+2p)",
    "defense_guard": "8(0)",
    "special": "-",
    "weight": "0",
    "cost": "3 sp"
  },
  "Degan": {
    "name": "Degan",
    "weapon_type": "Dagger, Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "6(-1c)",
    "thrust": "6(+1p)",
    "defense_guard": "7(0)",
    "special": "Fluid Thrusts, Light Blade",
    "weight": "0",
    "cost": "1 sp"
  },
  "Dirk": {
    "name": "Dirk",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "7(-1c)",
    "thrust": "6(+0p)",
    "defense_guard": "7(0)",
    "special": "Fluid Thrusts, Light Blade",
    "weight": "0",
    "cost": "4 cp"
  },
  "Khyber Knife": {
    "name": "Khyber Knife",
    "weapon_type": "Dagger, Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+0c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(0)",
    "special": "Draw 2, Thin Blade",
    "weight": "0",
    "cost": "10 cp"
  },
  "Knife (Large)": {
    "name": "Knife (Large)",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "S",
    "swing": "6(-1c)",
    "thrust": "6(+0p)",
    "defense_guard": "9(0)",
    "special": "Draw 1, Light Blade",
    "weight": "0",
    "cost": "7 cp"
  },
  "Knife (Small)": {
    "name": "Knife (Small)",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "6(-2c)",
    "thrust": "6(-1p)",
    "defense_guard": "9(0)",
    "special": "Draw 1, Light Blade, Thin Blade",
    "weight": "0",
    "cost": "6 cp"
  },
  "Kukri": {
    "name": "Kukri",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "S",
    "swing": "6(+1c)",
    "thrust": "7(+0p)",
    "defense_guard": "9(0)",
    "special": "Draw 2, Light Blade, Forward Swept",
    "weight": "0",
    "cost": "1 sp"
  },
  "Main Gauche": {
    "name": "Main Gauche",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "7(-1c)",
    "thrust": "7(+0p)",
    "defense_guard": "6(3)",
    "special": "Companion Weapon, Light Blade",
    "weight": "0",
    "cost": "3 sp"
  },
  "Misericorde": {
    "name": "Misericorde",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "9(-2c)",
    "thrust": "5(-2p)",
    "defense_guard": "10(0)",
    "special": "Fluid Thrusts, Light Blade, Thin Blade",
    "weight": "0",
    "cost": "3 cp"
  },
  "Navaja": {
    "name": "Navaja",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "6(+0c)",
    "thrust": "7(-1p)",
    "defense_guard": "8(0)",
    "special": "Draw 2, Light Blade",
    "weight": "0",
    "cost": "6 cp"
  },
  "Poignard": {
    "name": "Poignard",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "6(-1c)",
    "thrust": "6(+0p)",
    "defense_guard": "8(1)",
    "special": "Fluid Thrusts, Light Blade, Thin Blade",
    "weight": "0",
    "cost": "6 cp"
  },
  "Pugio": {
    "name": "Pugio",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "7(-1c)",
    "thrust": "6(+1p)",
    "defense_guard": "7(0)",
    "special": "Light Blade, Spatulate Tip 2",
    "weight": "0",
    "cost": "6 cp"
  },
  "Puukko": {
    "name": "Puukko",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "6(-1c)",
    "thrust": "6(-0p)",
    "defense_guard": "9(0)",
    "special": "Fluid Thrusts, Light Blade",
    "weight": "0",
    "cost": "4 cp"
  },
  "Rondel Dagger": {
    "name": "Rondel Dagger",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "S",
    "swing": "7(-1c)",
    "thrust": "6(+1p)",
    "defense_guard": "7(1)",
    "special": "Fluid Thrusts, Light Blade, Thin Blade",
    "weight": "0",
    "cost": "6 cp"
  },
  "Short Katzbalger": {
    "name": "Short Katzbalger",
    "weapon_type": "Dagger, Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+0c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(1)",
    "special": "Spatulate Tip 2",
    "weight": "0",
    "cost": "6 sp"
  },
  "Stiletto": {
    "name": "Stiletto",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "7(-1c)",
    "thrust": "6(+0p)",
    "defense_guard": "8(1)",
    "special": "Fluid Thrusts, Light Blade, Thin Blade",
    "weight": "0",
    "cost": "8 cp"
  },
  "Swordbreaker": {
    "name": "Swordbreaker",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "S",
    "swing": "6(-1c)",
    "thrust": "6(+0p)",
    "defense_guard": "7(1)",
    "special": "Companion Weapon, Parrying Teeth",
    "weight": "0",
    "cost": "1 sp"
  },
  "Tanto": {
    "name": "Tanto",
    "weapon_type": "Dagger",
    "hands": "1H",
    "reach": "H",
    "swing": "7(+0c)",
    "thrust": "6(+0p)",
    "defense_guard": "8(1)",
    "special": "Draw 1, Light Blade, Thin Blade",
    "weight": "0",
    "cost": "3 sp"
  },
  "Arming Sword (Early)": {
    "name": "Arming Sword (Early)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(1)",
    "special": "Spatulate Tip 2",
    "weight": "0.5",
    "cost": "1 gp"
  },
  "Arming Sword (Chivalric)": {
    "name": "Arming Sword (Chivalric)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+2c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(2)",
    "special": "-",
    "weight": "0.5",
    "cost": "1 gp"
  },
  "Arming Sword (Late)": {
    "name": "Arming Sword (Late)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+0c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(2)",
    "special": "-",
    "weight": "0.5",
    "cost": "1 gp"
  },
  "Backsword (Standard)": {
    "name": "Backsword (Standard)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(4)",
    "special": "-",
    "weight": "0.5",
    "cost": "1 gp"
  },
  "Backsword (Heavy)": {
    "name": "Backsword (Heavy)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "8(+1p)",
    "defense_guard": "8(3)",
    "special": "-",
    "weight": "0.5",
    "cost": "25 sp"
  },
  "Bastard Sword*": {
    "name": "Bastard Sword*",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+0c)",
    "thrust": "7(+1p)",
    "defense_guard": "8(2)",
    "special": "Heavy Weapon",
    "weight": "1",
    "cost": "50 sp"
  },
  "Claymore (Basket Hilted)": {
    "name": "Claymore (Basket Hilted)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(4)",
    "special": "Tight Grip",
    "weight": "0.5",
    "cost": "1 gp"
  },
  "Cutlass": {
    "name": "Cutlass",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1c)",
    "thrust": "8(+0p)",
    "defense_guard": "7(3)",
    "special": "-",
    "weight": "0.5",
    "cost": "1 sp"
  },
  "Dussack": {
    "name": "Dussack",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1c)",
    "thrust": "7(-1p)",
    "defense_guard": "7(3)",
    "special": "Draw 2, Tight Grip",
    "weight": "0.5",
    "cost": "1 sp"
  },
  "Espada Ropera": {
    "name": "Espada Ropera",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+0c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(3)",
    "special": "-",
    "weight": "0.5",
    "cost": "25 sp"
  },
  "Falcata": {
    "name": "Falcata",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "6(+1c)",
    "thrust": "8(-1p)",
    "defense_guard": "8(3)",
    "special": "Forward Swept",
    "weight": "0.5",
    "cost": "1 gp"
  },
  "Falchion": {
    "name": "Falchion",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+2c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(2)",
    "special": "-",
    "weight": "0.5",
    "cost": "18 cp"
  },
  "Gladius": {
    "name": "Gladius",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(0)",
    "special": "-",
    "weight": "0",
    "cost": "1 sp"
  },
  "Karthacki Dueling Sword": {
    "name": "Karthacki Dueling Sword",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "6(-1b)",
    "thrust": "6(+0p)",
    "defense_guard": "7(0)",
    "special": "Fluid Thrusts, Light Blade, Thin Blade",
    "weight": "0.5",
    "cost": "10 sp"
  },
  "Katana*": {
    "name": "Katana*",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "8(+1p)",
    "defense_guard": "8(1)",
    "special": "Draw 3, Heavy Weapon",
    "weight": "1",
    "cost": "50 sp"
  },
  "Katzbalger": {
    "name": "Katzbalger",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1c)",
    "thrust": "8(+0p)",
    "defense_guard": "7(2)",
    "special": "Spatulate Tip 2",
    "weight": "0.5",
    "cost": "4 sp"
  },
  "Katzbalger (Short)": {
    "name": "Katzbalger (Short)",
    "weapon_type": "Dagger, Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+0c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(1)",
    "special": "Spatulate Tip 2",
    "weight": "0",
    "cost": "6 sp"
  },
  "Kilij": {
    "name": "Kilij",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "8(+0p)",
    "defense_guard": "7(2)",
    "special": "Draw 4, Cavalry Sword",
    "weight": "0.5",
    "cost": "30 sp"
  },
  "Koncerz": {
    "name": "Koncerz",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "VL",
    "swing": "7(-2c)",
    "thrust": "8(+2p)",
    "defense_guard": "8(3)",
    "special": "AP Thrust 2, Couched Charge",
    "weight": "0.5",
    "cost": "25 sp"
  },
  "Khopesh": {
    "name": "Khopesh",
    "weapon_type": "Sword, Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "6(+1c)",
    "thrust": "9(-1p)",
    "defense_guard": "8(0)",
    "special": "Forward Swept, Hook",
    "weight": "0.5",
    "cost": "1 sp"
  },
  "Kriegsmesser*": {
    "name": "Kriegsmesser*",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(2)",
    "special": "Draw 2, Heavy Weapon",
    "weight": "1",
    "cost": "10 sp"
  },
  "Langes Messer": {
    "name": "Langes Messer",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "7(+0p)",
    "defense_guard": "8(2)",
    "special": "Draw 2",
    "weight": "0.5",
    "cost": "1 sp"
  },
  "Longsword*": {
    "name": "Longsword*",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+1c)",
    "thrust": "7(+0p)",
    "defense_guard": "8(2)",
    "special": "Heavy Weapon",
    "weight": "1",
    "cost": "50 sp"
  },
  "Pallasch": {
    "name": "Pallasch",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+1c)",
    "thrust": "8(+1p)",
    "defense_guard": "7(3)",
    "special": "Cavalry Sword",
    "weight": "0.5",
    "cost": "35 sp"
  },
  "Rapier": {
    "name": "Rapier",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "6(-1c)",
    "thrust": "6(+0p)",
    "defense_guard": "7(3)",
    "special": "Fluid Thrusts, Thin Blade",
    "weight": "0.5",
    "cost": "30 sp"
  },
  "Saber (Early)": {
    "name": "Saber (Early)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+0c)",
    "thrust": "7(+0p)",
    "defense_guard": "8(1)",
    "special": "Draw 2, Cavalry Sword",
    "weight": "0.5",
    "cost": "10 sp"
  },
  "Saber (Hussar)": {
    "name": "Saber (Hussar)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "7(-1p)",
    "defense_guard": "7(3)",
    "special": "Draw 3, Cavalry Sword",
    "weight": "0.5",
    "cost": "25 sp"
  },
  "Saber (Karabela)": {
    "name": "Saber (Karabela)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+0c)",
    "thrust": "8(-1p)",
    "defense_guard": "7(3)",
    "special": "Draw 4, Cavalry Sword",
    "weight": "0.5",
    "cost": "30 sp"
  },
  "Saber (Zellish)": {
    "name": "Saber (Zellish)",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+1c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(3)",
    "special": "Draw 2, Forward Swept",
    "weight": "0.5",
    "cost": "15 sp"
  },
  "Schiavona": {
    "name": "Schiavona",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+0c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(3)",
    "special": "Tight Grip",
    "weight": "0.5",
    "cost": "1 gp"
  },
  "Scimitar": {
    "name": "Scimitar",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+0c)",
    "thrust": "7(-1p)",
    "defense_guard": "7(2)",
    "special": "Draw 4, Cavalry Sword",
    "weight": "0.5",
    "cost": "15 sp"
  },
  "Scythe-Sword": {
    "name": "Scythe-Sword",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1c)",
    "thrust": "9(-1p)",
    "defense_guard": "8(1)",
    "special": "Draw 2, Forward Swept",
    "weight": "0.5",
    "cost": "16 cp"
  },
  "Shaska": {
    "name": "Shaska",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+0c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(0)",
    "special": "Draw 2, Cavalry Sword",
    "weight": ".5",
    "cost": "15 sp"
  },
  "Short Sword": {
    "name": "Short Sword",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+0c)",
    "thrust": "6(+1p)",
    "defense_guard": "7(1)",
    "special": "-",
    "weight": "0",
    "cost": "1 sp"
  },
  "Sidesword": {
    "name": "Sidesword",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+1c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(3)",
    "special": "-",
    "weight": "0.5",
    "cost": "15 sp"
  },
  "Smallsword": {
    "name": "Smallsword",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "6(-2c)",
    "thrust": "6(+0p)",
    "defense_guard": "7(3)",
    "special": "Fluid Thrusts, Light Blade, Thin Blade",
    "weight": "0.5",
    "cost": "30 sp"
  },
  "Spadroon": {
    "name": "Spadroon",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "6(-1c)",
    "thrust": "6(+0p)",
    "defense_guard": "7(3)",
    "special": "Fluid Thrusts, Light Blade",
    "weight": "0.5",
    "cost": "30 sp"
  },
  "Tesshake": {
    "name": "Tesshake",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1c)",
    "thrust": "7(+0p)",
    "defense_guard": "8(3)",
    "special": "-",
    "weight": "0.5",
    "cost": "1 sp"
  },
  "Tulwar": {
    "name": "Tulwar",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+0c)",
    "thrust": "7(-2p)",
    "defense_guard": "8(2)",
    "special": "Draw 4, Tight Grip, Cavalry Sword",
    "weight": "0.5",
    "cost": "25 sp"
  },
  "Urumi": {
    "name": "Urumi",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "VL",
    "swing": "7(+0c)",
    "thrust": "NA",
    "defense_guard": "9(1)",
    "special": "Chain 3, Draw 2",
    "weight": "0",
    "cost": "30 sp"
  },
  "Wakizashi": {
    "name": "Wakizashi",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+0c)",
    "thrust": "8(+0p)",
    "defense_guard": "7(1)",
    "special": "Draw 1",
    "weight": "0",
    "cost": "10 sp"
  },
  "War Cleaver": {
    "name": "War Cleaver",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+2c)",
    "thrust": "8(-1p)",
    "defense_guard": "8(0)",
    "special": "Heavy Weapon",
    "weight": "0.5",
    "cost": "6 cp"
  },
  "Yataghan": {
    "name": "Yataghan",
    "weapon_type": "Sword",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1c)",
    "thrust": "8(+0p)",
    "defense_guard": "7(0)",
    "special": "Forward Swept, Draw 1",
    "weight": "0.5",
    "cost": "10 sp"
  },
  "Bastard Sword": {
    "name": "Bastard Sword",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+1c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(2)",
    "special": "Hand-Off, Heavy Weapon",
    "weight": "1",
    "cost": "50 sp"
  },
  "Claymore": {
    "name": "Claymore",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(2)",
    "special": "Heavy Weapon",
    "weight": "2",
    "cost": "50 sp"
  },
  "Estoc": {
    "name": "Estoc",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "8(+0b)",
    "thrust": "6(+2p)",
    "defense_guard": "7(2)",
    "special": "AP Thrust 1, Thin Blade, Fluid Thrusts",
    "weight": "1",
    "cost": "45 sp"
  },
  "Flammenschwert": {
    "name": "Flammenschwert",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "8(+3p)",
    "defense_guard": "7(3)",
    "special": "Draw 1, Crushing 1, Heavy Weapon",
    "weight": "2",
    "cost": "4 gp"
  },
  "Godenak": {
    "name": "Godenak",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+3c)",
    "thrust": "8(-1p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 1, Heavy Weapon",
    "weight": "1",
    "cost": "2 sp"
  },
  "Grosses Messer": {
    "name": "Grosses Messer",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(1)",
    "special": "Draw 3, Heavy Weapon",
    "weight": "2",
    "cost": "1 gp"
  },
  "Katana": {
    "name": "Katana",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+2c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(1)",
    "special": "Draw 4, Hand-Off, Heavy Weapon",
    "weight": "1",
    "cost": "50 sp"
  },
  "Katzbalger (Large)": {
    "name": "Katzbalger (Large)",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "8(+0p)",
    "defense_guard": "7(2)",
    "special": "Spatulate Tip 2, Heavy Weapon",
    "weight": "1",
    "cost": "2 gp"
  },
  "Kriegsmesser": {
    "name": "Kriegsmesser",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+2c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(2)",
    "special": "Draw 3, Hand-Off, Heavy Weapon",
    "weight": "1",
    "cost": "10 sp"
  },
  "Longsword": {
    "name": "Longsword",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(2)",
    "special": "Hand-Off, Heavy Weapon",
    "weight": "1",
    "cost": "50 sp"
  },
  "Massive Godenak": {
    "name": "Massive Godenak",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+4c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Heavy Weapon, Freakishly Large",
    "weight": "2",
    "cost": "50 sp"
  },
  "Montante": {
    "name": "Montante",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(2)",
    "special": "Heavy Weapon",
    "weight": "2",
    "cost": "4 gp"
  },
  "No-Dachi": {
    "name": "No-Dachi",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(1)",
    "special": "Draw 3, Heavy Weapon",
    "weight": "1",
    "cost": "3 gp"
  },
  "Swiss Saber (Schnepf)": {
    "name": "Swiss Saber (Schnepf)",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+1c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(3)",
    "special": "Draw 3, Heavy Weapon",
    "weight": "1",
    "cost": "45 sp"
  },
  "Zweihander": {
    "name": "Zweihander",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+3c)",
    "thrust": "8(+2p)",
    "defense_guard": "7(2)",
    "special": "Heavy Weapon",
    "weight": "2",
    "cost": "75 sp"
  },
  "Zweihander (Grutte)": {
    "name": "Zweihander (Grutte)",
    "weapon_type": "Sword",
    "hands": "2H",
    "reach": "EL",
    "swing": "7(+4c)",
    "thrust": "8(+3p)",
    "defense_guard": "7(2)",
    "special": "Heavy Weapon, Freakishly Large",
    "weight": "3",
    "cost": "6 gp"
  },
  "Battleaxe": {
    "name": "Battleaxe",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+3c)",
    "thrust": "7(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 1, Hand-Off, Heavy Weapon, Hook, Thrusting Slot, Shock 2, Swinging Slot",
    "weight": "1",
    "cost": "6 sp"
  },
  "Bar Mace": {
    "name": "Bar Mace",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+1b)",
    "thrust": "7(-2b)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Shock 1, Thrusting Slot",
    "weight": "0",
    "cost": "1 sp"
  },
  "Club (Short)/ Truncheon": {
    "name": "Club (Short)/ Truncheon",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "6(+0b)",
    "thrust": "7(-2b)",
    "defense_guard": "6(0)",
    "special": "-",
    "weight": "0",
    "cost": "1 cp"
  },
  "Club (Medium)/ Rod": {
    "name": "Club (Medium)/ Rod",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+0b)",
    "thrust": "7(-1b)",
    "defense_guard": "6(0)",
    "special": "-",
    "weight": "0",
    "cost": "1 cp"
  },
  "Double-Headed Flail": {
    "name": "Double-Headed Flail",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "M",
    "swing": "8(+1b)",
    "thrust": "8(-2b)",
    "defense_guard": "10(0)",
    "special": "Chain 1, Multi-Hit Swing 2, Shock 2",
    "weight": "1",
    "cost": "9 cp"
  },
  "Hand Axe/ Hatchet": {
    "name": "Hand Axe/ Hatchet",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+2c)",
    "thrust": "7(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 1, Hook, Shock 1, Swing Slot, Thrusting Slot",
    "weight": "0",
    "cost": "6 cp"
  },
  "Light Flail": {
    "name": "Light Flail",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "M",
    "swing": "7(+2b)",
    "thrust": "8(-2b)",
    "defense_guard": "9(0)",
    "special": "Chain 2, Shock 2",
    "weight": "1",
    "cost": "6 sp"
  },
  "Light Mace (Flanged)": {
    "name": "Light Mace (Flanged)",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+2b)",
    "thrust": "7(-2b)",
    "defense_guard": "7(0)",
    "special": "AP Swing 2, Crushing 1, Shock 2, Thrusting Slot",
    "weight": "0",
    "cost": "3 sp"
  },
  "Light Mace (Knobbed)": {
    "name": "Light Mace (Knobbed)",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+2b)",
    "thrust": "7(-2b)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Shock 2, Thrusting Slot",
    "weight": "0",
    "cost": "4 cp"
  },
  "Light Mace (Spiked)": {
    "name": "Light Mace (Spiked)",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+2b)",
    "thrust": "7(-2b)",
    "defense_guard": "7(0)",
    "special": "Bleed 2, Shock 2, Thrusting Slot",
    "weight": "0",
    "cost": "8 cp"
  },
  "Tabarzin*": {
    "name": "Tabarzin*",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "8(+0p)",
    "defense_guard": "9",
    "special": "AP Swing 1, Hand-Off, Hook, Shock 1, Swinging Slot",
    "weight": "2",
    "cost": "10 sp"
  },
  "Warhammer (Standard)": {
    "name": "Warhammer (Standard)",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+2b)",
    "thrust": "7(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 1, Crushing 1, Reverse Slot, Shock 1, Thrusting Slot",
    "weight": "0",
    "cost": "6 cp"
  },
  "War Pick": {
    "name": "War Pick",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "S",
    "swing": "7(+2p)",
    "thrust": "7(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Hook, Reverse Slot, Thrusting Slot",
    "weight": "0",
    "cost": "2 sp"
  },
  "Arming Spike": {
    "name": "Arming Spike",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "-",
    "swing": "-",
    "thrust": "(+0p)",
    "defense_guard": "-",
    "special": "Weapon Attachment (Thrust)",
    "weight": "0",
    "cost": "1 cp"
  },
  "Reverse Blade": {
    "name": "Reverse Blade",
    "weapon_type": "Polearm",
    "hands": "-",
    "reach": "-",
    "swing": "7(+2c)",
    "thrust": "-",
    "defense_guard": "-",
    "special": "Heavy Weapon, Weapon Attachment (Swing)",
    "weight": "0",
    "cost": "6 cp"
  },
  "Reverse Hammer": {
    "name": "Reverse Hammer",
    "weapon_type": "Polearm",
    "hands": "-",
    "reach": "-",
    "swing": "7(+1b)",
    "thrust": "-",
    "defense_guard": "-",
    "special": "AP Swing 1, Crushing 1, Heavy Weapon, Shock 1, Weapon Attachment (Swing)",
    "weight": "0",
    "cost": "6 cp"
  },
  "Reverse Spike": {
    "name": "Reverse Spike",
    "weapon_type": "Polearm",
    "hands": "-",
    "reach": "-",
    "swing": "7(+1p)",
    "thrust": "-",
    "defense_guard": "-",
    "special": "AP Swing 2, Heavy Weapon, Hook, Weapon Attachment (Swing)",
    "weight": "0",
    "cost": "6 cp"
  },
  "Weighted Chain": {
    "name": "Weighted Chain",
    "weapon_type": "Blunt",
    "hands": "1H",
    "reach": "VL",
    "swing": "8(+1b)",
    "thrust": "-",
    "defense_guard": "8(0)",
    "special": "Chain 3, Hook, Shock 2, Weapon Attachment (Swing)",
    "weight": "1",
    "cost": "6 cp"
  },
  "Club (Large)": {
    "name": "Club (Large)",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "6(+1b)",
    "thrust": "7(-1b)",
    "defense_guard": "7(0)",
    "special": "Heavy Weapon, Shock 1, Thrusting Slot",
    "weight": "1",
    "cost": "3 cp"
  },
  "Iron Club (Large)": {
    "name": "Iron Club (Large)",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "6(+2b)",
    "thrust": "7(-1b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Crushing 2, Heavy Weapon, Shock 2, Thrusting Slot",
    "weight": "2",
    "cost": "6 cp"
  },
  "Dane Axe": {
    "name": "Dane Axe",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+4c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Crushing 2, Heavy Weapon, Hook, Shock 2",
    "weight": "2",
    "cost": "7 sp"
  },
  "Goedendag": {
    "name": "Goedendag",
    "weapon_type": "Blunt, Polearm",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+3b)",
    "thrust": "8(+2p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, AP Thrust 2, Crushing 1, Heavy Weapon, Shock 2",
    "weight": "2",
    "cost": "1 sp"
  },
  "Gunstock Club": {
    "name": "Gunstock Club",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+2b)",
    "thrust": "7(-1b)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Heavy Weapon, Shock 1, Swinging Slot",
    "weight": "1",
    "cost": "7 cp"
  },
  "Heavy Mace (Flanged)": {
    "name": "Heavy Mace (Flanged)",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+3b)",
    "thrust": "7(-2b)",
    "defense_guard": "7(0)",
    "special": "AP Swing 2, Crushing 2, Heavy Weapon, Shock 1",
    "weight": "1",
    "cost": "6 sp"
  },
  "Heavy Mace (Knobbed)": {
    "name": "Heavy Mace (Knobbed)",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+3b)",
    "thrust": "7(-2b)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Heavy Weapon, Shock 4",
    "weight": "1",
    "cost": "1 sp"
  },
  "Heavy Mace (Spiked)": {
    "name": "Heavy Mace (Spiked)",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+3b)",
    "thrust": "7(-2b)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Bleed 3, Crushing 1, Heavy Weapon",
    "weight": "1",
    "cost": "2 sp"
  },
  "Morningstar": {
    "name": "Morningstar",
    "weapon_type": "Polearm, Blunt",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+3b)",
    "thrust": "8(+1p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Bleed 3, Heavy Weapon",
    "weight": "5",
    "cost": "1 sp"
  },
  "Poleaxe": {
    "name": "Poleaxe",
    "weapon_type": "Polearm, Spear, Blunt",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, AP Thrust 1, Heavy Weapon, Shock 2, Swinging Slot, Thin Blade",
    "weight": "5",
    "cost": "8 sp"
  },
  "Pole-Flail": {
    "name": "Pole-Flail",
    "weapon_type": "Blunt, Polearm",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2b)",
    "thrust": "7(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Chain 2, Crushing 2, Heavy Weapon, Shock 2",
    "weight": "2",
    "cost": "2 sp"
  },
  "Tabarzin": {
    "name": "Tabarzin",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+3c)",
    "thrust": "8(+0p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Hand-Off, Heavy Weapon, Hook, Shock 2, Swinging Slot",
    "weight": "2",
    "cost": "10 sp"
  },
  "Warhammer (Heavy)": {
    "name": "Warhammer (Heavy)",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+2b)",
    "thrust": "7(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 1, Crushing 2, Heavy Weapon, Shock 2, Swinging Slot, Thrusting Slot",
    "weight": "1",
    "cost": "1 sp"
  },
  "War Maul": {
    "name": "War Maul",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+3b)",
    "thrust": "8(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 1, Crushing 2, Heavy Weapon, Shock 4",
    "weight": "2",
    "cost": "2 sp"
  },
  "Wood Axe": {
    "name": "Wood Axe",
    "weapon_type": "Blunt",
    "hands": "2H",
    "reach": "M",
    "swing": "7(+2c)",
    "thrust": "8(-2b)",
    "defense_guard": "8(0)",
    "special": "AP Swing 1, Heavy Weapon, Hook, Shock 2",
    "weight": "1",
    "cost": "2 sp"
  },
  "Ahlspiess": {
    "name": "Ahlspiess",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "L",
    "swing": "8(-1b)",
    "thrust": "7(+1p)",
    "defense_guard": "7(0)",
    "special": "AP Thrust 3,Thin Blade",
    "weight": "5",
    "cost": "4 sp"
  },
  "Fauchard": {
    "name": "Fauchard",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "8(+1p)",
    "defense_guard": "7(0)",
    "special": "Forward Swept, Heavy Weapon, Swinging Slot",
    "weight": "4",
    "cost": "1 sp"
  },
  "Ge (Chinese Dagger-Axe Halberd)": {
    "name": "Ge (Chinese Dagger-Axe Halberd)",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+3p)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Heavy Weapon, Hook",
    "weight": "5",
    "cost": "1 sp"
  },
  "Half-Pike*": {
    "name": "Half-Pike*",
    "weapon_type": "Spear",
    "hands": "1H",
    "reach": "L",
    "swing": "8(-2c)",
    "thrust": "7(+1p)",
    "defense_guard": "8(0)",
    "special": "Fluid Thrusts",
    "weight": "4",
    "cost": "1 sp"
  },
  "Half-Pike": {
    "name": "Half-Pike",
    "weapon_type": "Spear",
    "hands": "2H",
    "reach": "L",
    "swing": "7(-1c)",
    "thrust": "6(+2p)",
    "defense_guard": "7(0)",
    "special": "Fluid Thrusts, Hand-Off",
    "weight": "4",
    "cost": "1 sp"
  },
  "Lance (Light)": {
    "name": "Lance (Light)",
    "weapon_type": "Spear",
    "hands": "1H",
    "reach": "VL",
    "swing": "10(-1c)",
    "thrust": "8(+2p)",
    "defense_guard": "10(0)",
    "special": "Couched Charge, Heavy Weapon",
    "weight": "4",
    "cost": "1 cp"
  },
  "Lance (Heavy)": {
    "name": "Lance (Heavy)",
    "weapon_type": "Spear",
    "hands": "1H",
    "reach": "EL",
    "swing": "10(-1c)",
    "thrust": "9(+3p)",
    "defense_guard": "10(0)",
    "special": "Couched Charge, Heavy Weapon",
    "weight": "6",
    "cost": "1 sp"
  },
  "Lance (Hollow)": {
    "name": "Lance (Hollow)",
    "weapon_type": "Spear",
    "hands": "1H",
    "reach": "LL",
    "swing": "10(-1c)",
    "thrust": "9(+3p)",
    "defense_guard": "10(0)",
    "special": "Couched Charge, Heavy Weapon",
    "weight": "8",
    "cost": "4 sp"
  },
  "Longstaff": {
    "name": "Longstaff",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "EL",
    "swing": "7(+0b)",
    "thrust": "7(-1b)",
    "defense_guard": "7(0)",
    "special": "Heavy Weapon",
    "weight": "6",
    "cost": "4 cp"
  },
  "Military Fork": {
    "name": "Military Fork",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "10(-1c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(0)",
    "special": "Multi-Hit Thrust 2, Swinging Slot",
    "weight": "5",
    "cost": "3 cp"
  },
  "Musket (Butt)": {
    "name": "Musket (Butt)",
    "weapon_type": "Spear",
    "hands": "2H",
    "reach": "H",
    "swing": "7(+1b)",
    "thrust": "7(-1b)",
    "defense_guard": "8(0)",
    "special": "Heavy Weapon, Shock 2",
    "weight": "0",
    "cost": "-"
  },
  "Musket (Bayonet)": {
    "name": "Musket (Bayonet)",
    "weapon_type": "Spear",
    "hands": "2H",
    "reach": "L",
    "swing": "9(-1c)",
    "thrust": "7(+2p)",
    "defense_guard": "8(0)",
    "special": "Heavy Weapon, Thin Blade",
    "weight": "0",
    "cost": "3 cp"
  },
  "Partisan": {
    "name": "Partisan",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "EL",
    "swing": "8(+2c)",
    "thrust": "7(+3p)",
    "defense_guard": "7(0)",
    "special": "Fluid Thrusts",
    "weight": "5",
    "cost": "10 sp"
  },
  "Pike": {
    "name": "Pike",
    "weapon_type": "Spear",
    "hands": "2H",
    "reach": "LL",
    "swing": "10(-2c)",
    "thrust": "8(+3p)",
    "defense_guard": "9(0)",
    "special": "Brace",
    "weight": "6",
    "cost": "1 sp"
  },
  "Quarterstaff": {
    "name": "Quarterstaff",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "6(+0b)",
    "thrust": "6(-1b)",
    "defense_guard": "6(0)",
    "special": "Fluid Thrusts, Heavy Weapon",
    "weight": "4",
    "cost": "3 cp"
  },
  "Ranseur": {
    "name": "Ranseur",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "EL",
    "swing": "8(+0c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "-",
    "weight": "5",
    "cost": "1 sp"
  },
  "Spear (Arming)*": {
    "name": "Spear (Arming)*",
    "weapon_type": "Spear",
    "hands": "1H",
    "reach": "VL",
    "swing": "9(-1c)",
    "thrust": "7(+1p)",
    "defense_guard": "9(0)",
    "special": "-",
    "weight": "4",
    "cost": "6 cp"
  },
  "Spear (Arming)": {
    "name": "Spear (Arming)",
    "weapon_type": "Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+0c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "Fluid Thrusts, Hand-Off",
    "weight": "4",
    "cost": "6 cp"
  },
  "Spear (Short)": {
    "name": "Spear (Short)",
    "weapon_type": "Spear",
    "hands": "1H",
    "reach": "M",
    "swing": "8(+0c)",
    "thrust": "7(+2p)",
    "defense_guard": "8(0)",
    "special": "Fluid Thrusts",
    "weight": "0",
    "cost": "3 cp"
  },
  "Spear (Standard)*": {
    "name": "Spear (Standard)*",
    "weapon_type": "Spear",
    "hands": "1H",
    "reach": "EL",
    "swing": "9(+0c)",
    "thrust": "7(+2p)",
    "defense_guard": "9(0)",
    "special": "-",
    "weight": "4",
    "cost": "8 cp"
  },
  "Spear (Standard)": {
    "name": "Spear (Standard)",
    "weapon_type": "Spear",
    "hands": "2H",
    "reach": "EL",
    "swing": "8(+0c)",
    "thrust": "7(+3p)",
    "defense_guard": "8(0)",
    "special": "Fluid Thrusts, Hand-Off",
    "weight": "4",
    "cost": "8 cp"
  },
  "Spetum": {
    "name": "Spetum",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "8(+1c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "Fluid Thrusts",
    "weight": "4",
    "cost": "2 sp"
  },
  "Swordstaff": {
    "name": "Swordstaff",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "EL",
    "swing": "8(+3c)",
    "thrust": "7(+3p)",
    "defense_guard": "8(0)",
    "special": "-",
    "weight": "8",
    "cost": "3 sp"
  },
  "Trident*": {
    "name": "Trident*",
    "weapon_type": "Polearm, Spear",
    "hands": "1H",
    "reach": "L",
    "swing": "10(-1c)",
    "thrust": "8(-1p)",
    "defense_guard": "9(0)",
    "special": "Multi-Hit Thrust 3",
    "weight": "4",
    "cost": "5 cp"
  },
  "Trident": {
    "name": "Trident",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "L",
    "swing": "9(+0c)",
    "thrust": "7(+0p)",
    "defense_guard": "7(0)",
    "special": "Hand-Off, Multi-Hit Thrust 3",
    "weight": "4",
    "cost": "5 cp"
  },
  "Yari (Jumonji)": {
    "name": "Yari (Jumonji)",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "Heavy Weapon,",
    "weight": "4",
    "cost": "2 sp"
  },
  "Yari (Bishamon)": {
    "name": "Yari (Bishamon)",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+3c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1",
    "weight": "4",
    "cost": "3 sp"
  },
  "Yari (Kata Kama)": {
    "name": "Yari (Kata Kama)",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2p/+2c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Heavy Weapon, Hook",
    "weight": "4",
    "cost": "3 sp"
  },
  "Bardiche": {
    "name": "Bardiche",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+4c)",
    "thrust": "9(-1p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Crushing 2, Heavy Weapon, Shock 2, Swinging Slot",
    "weight": "5",
    "cost": "2 sp"
  },
  "Bec de Corbin": {
    "name": "Bec de Corbin",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2p)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 2, Heavy Weapon, Hook, Swinging Slot,Thin Blade",
    "weight": "5",
    "cost": "1 sp"
  },
  "Bill (Black)": {
    "name": "Bill (Black)",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "8(+3c)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Crushing 1, Heavy Weapon, Hook, Shock 2, Swinging Slot",
    "weight": "5",
    "cost": "1 sp"
  },
  "Bill (Forest)": {
    "name": "Bill (Forest)",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "EL",
    "swing": "8(+2c)",
    "thrust": "7(+2p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Crushing 1, Heavy Weapon, Hook, Shock 2, Swinging Slot",
    "weight": "5",
    "cost": "1 sp"
  },
  "Falx": {
    "name": "Falx",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "L",
    "swing": "8(+3c)",
    "thrust": "10(-1p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Forward Swept, Heavy Weapon",
    "weight": "4",
    "cost": "1 sp"
  },
  "Glaive": {
    "name": "Glaive",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "8(+1p)",
    "defense_guard": "7(0)",
    "special": "Draw 2, Heavy Weapon, Swinging Slot",
    "weight": "5",
    "cost": "3 sp"
  },
  "Guandao (Chinese Glaive)": {
    "name": "Guandao (Chinese Glaive)",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "8(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Draw 2, Heavy Weapon",
    "weight": "5",
    "cost": "5 sp"
  },
  "Halberd": {
    "name": "Halberd",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+3c)",
    "thrust": "8(+2p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 2, Crushing 2, Heavy Weapon, Swinging Slot",
    "weight": "5",
    "cost": "3 sp"
  },
  "Lochaber Axe": {
    "name": "Lochaber Axe",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "8(+1p)",
    "defense_guard": "8(0)",
    "special": "AP Swing 2, Heavy Weapon, Hook, Shock 2",
    "weight": "5",
    "cost": "2 sp"
  },
  "Lucerne Hammer": {
    "name": "Lucerne Hammer",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "L",
    "swing": "7(+2b)",
    "thrust": "7(+2p)",
    "defense_guard": "7(0)",
    "special": "Crushing 2, Shock 2, AP Thrust 1, Heavy Weapon, Swinging Slot, Thin Blade",
    "weight": "5",
    "cost": "8 sp"
  },
  "Naginata": {
    "name": "Naginata",
    "weapon_type": "Polearm, Spear",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+2c)",
    "thrust": "7(+1p)",
    "defense_guard": "7(0)",
    "special": "Draw 2, Fluid Thrusts",
    "weight": "4",
    "cost": "10 sp"
  },
  "Saber-Halberd": {
    "name": "Saber-Halberd",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+3c)",
    "thrust": "8(+0p)",
    "defense_guard": "7(0)",
    "special": "AP Swing 1, Crushing 1, Draw 2, Heavy Weapon, Swinging Slot",
    "weight": "5",
    "cost": "15 sp"
  },
  "War-Scythe": {
    "name": "War-Scythe",
    "weapon_type": "Polearm",
    "hands": "2H",
    "reach": "VL",
    "swing": "7(+3c)",
    "thrust": "9(+0p)",
    "defense_guard": "8(0)",
    "special": "Forward Swept, Heavy Weapon,",
    "weight": "4",
    "cost": "4 cp"
  }
};

const missile_weapon_special_qualities = {
  "AP Swing[X]": {
    "quality": "AP Swing[X]",
    "effect": "Armor Piercing Swing[X].When making a Swinging attack against a Hit Location with Hard armor protection, this weapon inflicts X additional damage, up to the AV of the Armor."
  },
  "AP Thrust[X]": {
    "quality": "AP Thrust[X]",
    "effect": "Armor Piercing Thrust[X].When making a Thrusting attack against a Hit Location with Hard armor protection, this weapon inflicts X additional damage, up to the AV of the Armor."
  },
  "Bleed[X]": {
    "quality": "Bleed[X]",
    "effect": "Any Swinging attack from this weapon that either inflicts a Wound, or fails to inflict a Wound by 2 or fewer damage, inflicts X Blood Loss."
  },
  "Brace": {
    "quality": "Brace",
    "effect": "When using this weapon, you gain 2 automatic successes on Initiative Tests made as a result of Offensive / Offensive Orientation."
  },
  "Cavalry Sword": {
    "quality": "Cavalry Sword",
    "effect": "When being used during a Ride - By Attack or a Charge while Mounted, this weapon inflicts + 1 damage on Swings, and triggers the Draw quality on 2 BS or more"
  },
  "Chain[X]": {
    "quality": "Chain[X]",
    "effect": "Any attack made at Swing TN with this weapon ignores the first X successes of an enemy’ s Parrying or Blocking defense, Maneuvers like Riposte and Arm Parry.Additionally, this weapon can neither engage in , nor be engaged in a Hilt Push of any sort."
  },
  "Companion Weapon": {
    "quality": "Companion Weapon",
    "effect": "When this weapon is used to make any sort of defensive Maneuver, one of the dice devoted automatically succeeds before rolling."
  },
  "Couched Charge": {
    "quality": "Couched Charge",
    "effect": "When making a Lance Charge attack with this weapon, reduce its Thrusting TN by 2, and use the Horse’ s STR as the base for damage instead of your own.However, your Reach is not increased by the Tall Boon.In addition, if a Lance Charge attack made by this weapon is Blocked, it carries through on the intended Target Zone anyway, as though it hit with 0 BS, and is reduced by the Shield’ s AV regardless of where it hit.If the total damage inflicted by an attack that takes advantage of Lance Charge exceeds the Durability of the weapon by 5 or more, then the weapon breaks immediately after the attack is made."
  },
  "Crushing[X]": {
    "quality": "Crushing[X]",
    "effect": "When this weapon successfully hits with a Swing attack on a Hit Location with any sort of Hard armor protection, reduce all AVs of the armor on that Hit Location by X.This is done after damage is resolved for this attack, and only affects future attacks.Only the highest AV armor on that location is reduced by Crushing.If that armor is reduced to AV 0 in all areas, then Crushing begins to affect lesser Hard armors beneath it."
  },
  "Draw[X]": {
    "quality": "Draw[X]",
    "effect": "When making a Swinging attack that would inflict cutting damage with this weapon, inflict X additional cutting damage if you roll 3 or more BS.This special rule does not come into play if the target benefits from any sort of Hard armor on the Hit Location being hit."
  },
  "Fluid Thrusts": {
    "quality": "Fluid Thrusts",
    "effect": "This weapon can Feint from a Thrust."
  },
  "Forward Swept": {
    "quality": "Forward Swept",
    "effect": "When this weapon is used in a Swing attack against which the target would receive an AV bonus, use the lower value between the armor’ s AVC and AVP.The Swing still inflicts cutting damage regardless of which AV is used."
  },
  "Freakishly Large": {
    "quality": "Freakishly Large",
    "effect": "This weapon is so massive that unless the character using it has either 9 STR or the greater Tall Boon, the TNs for the weapon are all increased by 1."
  },
  "Hand-Off": {
    "quality": "Hand-Off",
    "effect": "This weapon can be wielded with one hand in addition to wielding with both hands. If used in this fashion, you may continue using it with its normal Proficiency, or with a 1 H version of either Blunt or Sword proficiency(depending on the base type of the weapon).However, instead of using the normal profile of the weapon, use the 1 H version of the weapon with an * next to it.Switching from 1 H to 2 H versions of a weapon can be done at the beginning of any Action(or in response to an injury) and requires no CP expenditure."
  },
  "Heavy Weapon": {
    "quality": "Heavy Weapon",
    "effect": "When weapons with the Light Blade quality Parry Swinging attacks from this weapon, the Defense TN of the Light Blade is increased by 2, instead of 1."
  },
  "Hook": {
    "quality": "Hook",
    "effect": "This weapon can be used with the Hook Maneuver."
  },
  "Light Blade": {
    "quality": "Light Blade",
    "effect": "When Parrying Swinging attacks from any weapon that does not have this quality, this weapon’ s Defense TN is increased by 1. Against Heavy Weapons, this penalty increases to 2."
  },
  "Multi-Hit[Y][X]": {
    "quality": "Multi-Hit[Y][X]",
    "effect": "When this weapon is used in a Y type(Swing or Thrust) attack that targets Hit Locations that successfully hits the target, instead of resolving one attack, X identical attacks of equal strength hit instead.Roll on the Target Zone as normal for the first hit.The second hit lands as though the roll had been one lower, the third hit as though the roll had been one higher."
  },
  "Parrying Teeth": {
    "quality": "Parrying Teeth",
    "effect": "-1 Parry TN vs attacks made by Swords and Daggers."
  },
  "Shock[X]": {
    "quality": "Shock[X]",
    "effect": "Any hit from this weapon inflicts additional Stun equal to the listed number.If the hit also causes a Wound, the Stun from Shock adds to the Stun from the Wound."
  },
  "Spatulate Tip[X]": {
    "quality": "Spatulate Tip[X]",
    "effect": "When making a Thrusting attack that would inflict Piercing damage with this weapon, inflict X additional cutting damage if you roll 3 or more BS.This special rule does not come into play if the target benefits from any sort of Hard armor on the Hit Location being hit."
  },
  "Swinging Slot": {
    "quality": "Swinging Slot",
    "effect": "This weapon can have a Swinging Weapon Attachment added to its Swing profile.This does not replace the current Swing profile, but can be used instead of it when declaring a Maneuver."
  },
  "Thin Blade": {
    "quality": "Thin Blade",
    "effect": "When making a Joint Thrust attack, this weapon’ s Thrust TN is decreased by 1. In addition, against mail armor this weapon gains AP Thrust 1. If the weapon has an AP Thrust quality already, do not combine these--use the higher one."
  },
  "Thrusting Slot": {
    "quality": "Thrusting Slot",
    "effect": "This weapon can have its Thrust profile replaced with a Thrusting Weapon Attachment."
  },
  "Tight Grip": {
    "quality": "Tight Grip",
    "effect": "When using the Power Attack option on a Swing attack, inflict 1 additional damage.When making a Stability Test to retain your weapon against a Disarm Maneuver or similar event, you may roll 2 additional dice."
  },
  "Weapon Attachment": {
    "quality": "Weapon Attachment",
    "effect": "This weapon can be attached to any weapon with a Swinging Slot(for Reverse Weapons) or a Thrusting Slot(for Arming Spikes) and used instead of the weapon’ s basic swinging / thrusting profile.When using the Weapon Attachment, use its attack TN and Damage instead of the original where listed, use the original where no new number is listed. e.g.A Battleaxe with a Reverse Spike Weapon Attachment can make a Strike using the stats of a Reverse Spike instead of the stats of the Battleaxe."
  }
};