import { Float, Integer } from "../../../utilities/utilities";

export interface APV {
  readonly family: ArmorMaterialFamily;
  readonly name: string;
  readonly surface: Integer.Unsigned;
  readonly cut: Integer.Unsigned;
  readonly chop: Integer.Unsigned;
  readonly pierce: Integer.Unsigned;
  readonly thrust: Integer.Unsigned;
  readonly impact: Integer.Unsigned;
  readonly flanged: Integer.Unsigned;
  readonly weight_per_position: Float.Signed;
}

export enum ArmorMaterialFamily {
  None = 'none',
}

MML.APVList = {
  'None': {
    family: ArmorMaterialFamily.None,
    name: 'None',
    surface: 0,
    cut: 0,
    chop: 0,
    pierce: 0,
    thrust: 0,
    impact: 0,
    flanged: 0,
    weight_per_position: 0
  },
  'Greater Steel Coat of Lames, Leather, Medium': {
    family: 'Coat of Lames',
    name: 'Greater Steel Coat of Lames, Leather, Medium',
    surface: 34,
    cut: 29,
    chop: 19,
    pierce: 30,
    thrust: 19,
    impact: 18,
    flanged: 13,
    weight_per_position: 2.12
  },
  'Greater Steel Coat of Lames, Cloth, Medium': {
    family: 'Coat of Lames',
    name: 'Greater Steel Coat of Lames, Cloth, Medium',
    surface: 33,
    cut: 28,
    chop: 18,
    pierce: 30,
    thrust: 19,
    impact: 16,
    flanged: 12,
    weight_per_position: 1.87
  },
  'Hardened Leather Coat of Lames, Leather, Medium': {
    family: 'Coat of Lames',
    name: 'Hardened Leather Coat of Lames, Leather, Medium',
    surface: 15,
    cut: 14,
    chop: 10,
    pierce: 15,
    thrust: 10,
    impact: 10,
    flanged: 6,
    weight_per_position: 1.14
  },
  'Greater Steel Coat of Plates, Leather, Medium': {
    family: 'Coat of Plates',
    name: 'Greater Steel Coat of Plates, Leather, Medium',
    surface: 27,
    cut: 23,
    chop: 15,
    pierce: 23,
    thrust: 16,
    impact: 10,
    flanged: 9,
    weight_per_position: 1.81
  },
  'Greater Steel Coat of Plates, Cloth, Medium': {
    family: 'Coat of Plates',
    name: 'Greater Steel Coat of Plates, Cloth, Medium',
    surface: 26,
    cut: 25,
    chop: 14,
    pierce: 23,
    thrust: 16,
    impact: 8,
    flanged: 8,
    weight_per_position: 1.55
  },
  'Mannish High Steel Coat of Plates, Leather, Medium': {
    family: 'Coat of Plates',
    name: 'Mannish High Steel Coat of Plates, Leather, Medium',
    surface: 31,
    cut: 28,
    chop: 17,
    pierce: 26,
    thrust: 19,
    impact: 11,
    flanged: 10,
    weight_per_position: 1.81
  },
  'Greater Steel Coat of Scales, Leather, Medium': {
    family: 'Coat of Scales',
    name: 'Greater Steel Coat of Scales, Leather, Medium',
    surface: 34,
    cut: 24,
    chop: 17,
    pierce: 22,
    thrust: 15,
    impact: 15,
    flanged: 10,
    weight_per_position: 1.91
  },
  'Greater Steel Coat of Scales, Cloth, Medium': {
    family: 'Coat of Scales',
    name: 'Greater Steel Coat of Scales, Cloth, Medium',
    surface: 33,
    cut: 23,
    chop: 16,
    pierce: 21,
    thrust: 14,
    impact: 13,
    flanged: 9,
    weight_per_position: 1.66
  },
  'Hardened Leather Coat of Scales, Leather, Medium': {
    family: 'Coat of Scales',
    name: 'Hardened Leather Coat of Scales, Leather, Medium',
    surface: 14,
    cut: 14,
    chop: 9,
    pierce: 12,
    thrust: 9,
    impact: 7,
    flanged: 5,
    weight_per_position: 1.05
  },
  'Mannish High Steel Coat of Scales, Leather, Medium': {
    family: 'Coat of Scales',
    name: 'Mannish High Steel Coat of Scales, Leather, Medium',
    surface: 39,
    cut: 27,
    chop: 19,
    pierce: 25,
    thrust: 17,
    impact: 17,
    flanged: 11,
    weight_per_position: 1.91
  },
  'Mannish Cloth, Light': {
    family: 'Cloth',
    name: 'Mannish Cloth, Light',
    surface: 2,
    cut: 2,
    chop: 2,
    pierce: 2,
    thrust: 2,
    impact: 1,
    flanged: 1,
    weight_per_position: 0.04
  },
  'Mannish Cloth, Medium': {
    family: 'Cloth',
    name: 'Mannish Cloth, Medium',
    surface: 4,
    cut: 3,
    chop: 3,
    pierce: 3,
    thrust: 3,
    impact: 1,
    flanged: 2,
    weight_per_position: 0.08
  },
  'Mannish Cloth, Heavy': {
    family: 'Cloth',
    name: 'Mannish Cloth, Heavy',
    surface: 6,
    cut: 5,
    chop: 4,
    pierce: 5,
    thrust: 5,
    impact: 2,
    flanged: 2,
    weight_per_position: 0.24
  },
  'Mannish Quilt': {
    family: 'Cloth',
    name: 'Mannish Quilt',
    surface: 8,
    cut: 6,
    chop: 6,
    pierce: 7,
    thrust: 5,
    impact: 8,
    flanged: 7,
    weight_per_position: 0.15
  },
  'Mannish Silk': {
    family: 'Cloth',
    name: 'Mannish Silk',
    surface: 5,
    cut: 4,
    chop: 3,
    pierce: 4,
    thrust: 4,
    impact: 2,
    flanged: 2,
    weight_per_position: 0.06
  },
  'Fur, Light': {
    family: 'Light Leather',
    name: 'Fur, Light',
    surface: 10,
    cut: 6,
    chop: 6,
    pierce: 6,
    thrust: 5,
    impact: 6,
    flanged: 6,
    weight_per_position: 0.2
  },
  'Fur, Medium': {
    family: 'Light Leather',
    name: 'Fur, Medium',
    surface: 10,
    cut: 6,
    chop: 6,
    pierce: 6,
    thrust: 5,
    impact: 6,
    flanged: 7,
    weight_per_position: 0.4
  },
  'Fur, Heavy': {
    family: 'Heavy Leather',
    name: 'Fur, Heavy',
    surface: 11,
    cut: 8,
    chop: 8,
    pierce: 7,
    thrust: 7,
    impact: 7,
    flanged: 8,
    weight_per_position: 0.6
  },
  'Hardened Leather, Medium': {
    family: 'Heavy Leather',
    name: 'Hardened Leather, Medium',
    surface: 10,
    cut: 9,
    chop: 6,
    pierce: 9,
    thrust: 8,
    impact: 5,
    flanged: 4,
    weight_per_position: 0.64
  },
  'Hardened Leather, Heavy': {
    family: 'Heavy Leather',
    name: 'Hardened Leather, Heavy',
    surface: 14,
    cut: 12,
    chop: 8,
    pierce: 13,
    thrust: 10,
    impact: 7,
    flanged: 6,
    weight_per_position: 0.96
  },
  'Hardened Leather Lames, Medium': {
    family: 'Heavy Leather',
    name: 'Hardened Leather Lames, Medium',
    surface: 12,
    cut: 9,
    chop: 6,
    pierce: 10,
    thrust: 6,
    impact: 6,
    flanged: 4,
    weight_per_position: 0.77
  },
  'Hardened Leather Lames, Heavy': {
    family: 'Heavy Leather',
    name: 'Hardened Leather Lames, Heavy',
    surface: 16,
    cut: 13,
    chop: 8,
    pierce: 13,
    thrust: 8,
    impact: 8,
    flanged: 6,
    weight_per_position: 1.15
  },
  'Hardened Leather Scales, Medium': {
    family: 'Heavy Leather',
    name: 'Hardened Leather Scales, Medium',
    surface: 12,
    cut: 10,
    chop: 6,
    pierce: 8,
    thrust: 6,
    impact: 5,
    flanged: 4,
    weight_per_position: 0.68
  },
  'Hardened Leather Scales, Heavy': {
    family: 'Heavy Leather',
    name: 'Hardened Leather Scales, Heavy',
    surface: 16,
    cut: 13,
    chop: 8,
    pierce: 11,
    thrust: 8,
    impact: 7,
    flanged: 6,
    weight_per_position: 1.30
  },
  'Hide, Light': {
    family: 'Light Leather',
    name: 'Hide, Light',
    surface: 5,
    cut: 2,
    chop: 2,
    pierce: 2,
    thrust: 2,
    impact: 2,
    flanged: 2,
    weight_per_position: 0.14
  },
  'Hide, Heavy': {
    family: 'Heavy Leather',
    name: 'Hide, Heavy',
    surface: 6,
    cut: 3,
    chop: 4,
    pierce: 3,
    thrust: 3,
    impact: 4,
    flanged: 3,
    weight_per_position: 0.42
  },
  'Leather, Light': {
    family: 'Light Leather',
    name: 'Leather, Light',
    surface: 5,
    cut: 3,
    chop: 4,
    pierce: 3,
    thrust: 3,
    impact: 4,
    flanged: 3,
    weight_per_position: 0.16
  },
  'Leather, Medium': {
    family: 'Light Leather',
    name: 'Leather, Medium',
    surface: 6,
    cut: 5,
    chop: 5,
    pierce: 4,
    thrust: 4,
    impact: 5,
    flanged: 4,
    weight_per_position: 0.32
  },
  'Leather, Heavy': {
    family: 'Heavy Leather',
    name: 'Leather, Heavy',
    surface: 9,
    cut: 8,
    chop: 8,
    pierce: 7,
    thrust: 7,
    impact: 7,
    flanged: 7,
    weight_per_position: 0.48
  },
  'Mannish Padded': {
    family: 'Padded',
    name: 'Mannish Padded',
    surface: 11,
    cut: 8,
    chop: 9,
    pierce: 9,
    thrust: 7,
    impact: 10,
    flanged: 9,
    weight_per_position: 0.40
  },
  'Laced Mail of Common Steel, Medium': {
    family: 'Heavy Mail',
    name: 'Laced Mail of Common Steel, Medium',
    surface: 20,
    cut: 17,
    chop: 9,
    pierce: 15,
    thrust: 10,
    impact: 5,
    flanged: 6,
    weight_per_position: 1.30
  },
  'Laced Mail of Greater Steel, Medium': {
    family: 'Heavy Mail',
    name: 'Laced Mail of Greater Steel, Medium',
    surface: 24,
    cut: 20,
    chop: 11,
    pierce: 18,
    thrust: 12,
    impact: 6,
    flanged: 7,
    weight_per_position: 1.30
  },
  'Laced Mail of Mannish High Steel, Medium': {
    family: 'Heavy Mail',
    name: 'Laced Mail of Mannish High Steel, Medium',
    surface: 28,
    cut: 23,
    chop: 13,
    pierce: 21,
    thrust: 15,
    impact: 7,
    flanged: 8,
    weight_per_position: 1.30
  },
  'Laced Mail of Wrought Iron, Medium': {
    family: 'Heavy Mail',
    name: 'Laced Mail of Wrought Iron, Medium',
    surface: 12,
    cut: 10,
    chop: 5,
    pierce: 9,
    thrust: 6,
    impact: 3,
    flanged: 3,
    weight_per_position: 1.29
  },
  'Lames of Common Steel, Medium': {
    family: 'Lames',
    name: 'Lames of Common Steel, Medium',
    surface: 26,
    cut: 20,
    chop: 13,
    pierce: 21,
    thrust: 13,
    impact: 11,
    flanged: 9,
    weight_per_position: 1.70
  },
  'Lames of Greater Steel, Medium': {
    family: 'Lames',
    name: 'Lames of Greater Steel, Medium',
    surface: 31,
    cut: 24,
    chop: 15,
    pierce: 25,
    thrust: 15,
    impact: 14,
    flanged: 11,
    weight_per_position: 1.70
  },
  'Lames of Mannish High Steel, Light': {
    family: 'Lames',
    name: 'Lames of Mannish High Steel, Light',
    surface: 32,
    cut: 20,
    chop: 13,
    pierce: 20,
    thrust: 13,
    impact: 12,
    flanged: 9,
    weight_per_position: 1.28
  },
  'Lames of Mannish High Steel, Medium': {
    family: 'Lames',
    name: 'Lames of Mannish High Steel, Medium',
    surface: 36,
    cut: 26,
    chop: 18,
    pierce: 29,
    thrust: 18,
    impact: 16,
    flanged: 13,
    weight_per_position: 1.70
  },
  'Lames of Wrought Iron, Medium': {
    family: 'Lames',
    name: 'Lames of Wrought Iron, Medium',
    surface: 15,
    cut: 12,
    chop: 8,
    pierce: 13,
    thrust: 8,
    impact: 7,
    flanged: 6,
    weight_per_position: 1.68
  },
  'Brazed Mail of Greater Steel': {
    family: 'Light Mail',
    name: 'Brazed Mail of Greater Steel',
    surface: 22,
    cut: 19,
    chop: 12,
    pierce: 20,
    thrust: 14,
    impact: 6,
    flanged: 6,
    weight_per_position: 1.30
  },
  'Brazed Mail of Mannish High Steel': {
    family: 'Light Mail',
    name: 'Brazed Mail of Mannish High Steel',
    surface: 25,
    cut: 22,
    chop: 13,
    pierce: 24,
    thrust: 17,
    impact: 7,
    flanged: 7,
    weight_per_position: 1.30
  },
  'Butted Mail of Common Steel': {
    family: 'Light Mail',
    name: 'Butted Mail of Common Steel',
    surface: 16,
    cut: 14,
    chop: 8,
    pierce: 14,
    thrust: 8,
    impact: 4,
    flanged: 4,
    weight_per_position: 0.95
  },
  'Butted Mail of Greater Steel': {
    family: 'Light Mail',
    name: 'Butted Mail of Greater Steel',
    surface: 19,
    cut: 17,
    chop: 9,
    pierce: 16,
    thrust: 9,
    impact: 5,
    flanged: 5,
    weight_per_position: 0.95
  },
  'Butted Mail of Wrought Iron': {
    family: 'Light Mail',
    name: 'Butted Mail of Wrought Iron',
    surface: 10,
    cut: 8,
    chop: 5,
    pierce: 8,
    thrust: 5,
    impact: 2,
    flanged: 2,
    weight_per_position: 0.94
  },
  'Double Mail of Common Steel': {
    family: 'Light Mail',
    name: 'Double Mail of Common Steel',
    surface: 18,
    cut: 16,
    chop: 9,
    pierce: 16,
    thrust: 10,
    impact: 5,
    flanged: 4,
    weight_per_position: 1.30
  },
  'Double Mail of Greater Steel': {
    family: 'Light Mail',
    name: 'Double Mail of Greater Steel',
    surface: 22,
    cut: 19,
    chop: 11,
    pierce: 19,
    thrust: 12,
    impact: 6,
    flanged: 5,
    weight_per_position: 1.30
  },
  'Double Mail of Mannish High Steel': {
    family: 'Light Mail',
    name: 'Double Mail of Mannish High Steel',
    surface: 25,
    cut: 22,
    chop: 13,
    pierce: 22,
    thrust: 15,
    impact: 7,
    flanged: 6,
    weight_per_position: 1.30
  },
  'Single Mail of Common Steel': {
    family: 'Light Mail',
    name: 'Single Mail of Common Steel',
    surface: 17,
    cut: 15,
    chop: 8,
    pierce: 15,
    thrust: 10,
    impact: 4,
    flanged: 4,
    weight_per_position: 1
  },
  'Single Mail of Greater Steel': {
    family: 'Light Mail',
    name: 'Single Mail of Greater Steel',
    surface: 20,
    cut: 18,
    chop: 10,
    pierce: 18,
    thrust: 12,
    impact: 5,
    flanged: 5,
    weight_per_position: 1
  },
  'Single Mail of Mannish High Steel': {
    family: 'Light Mail',
    name: 'Single Mail of Mannish High Steel',
    surface: 24,
    cut: 21,
    chop: 12,
    pierce: 21,
    thrust: 13,
    impact: 6,
    flanged: 6,
    weight_per_position: 1
  },
  'Single Mail of Wrought Iron': {
    family: 'Light Mail',
    name: 'Single Mail of Wrought Iron',
    surface: 10,
    cut: 9,
    chop: 5,
    pierce: 9,
    thrust: 6,
    impact: 2,
    flanged: 2,
    weight_per_position: 0.99
  },
  'Plates of Common Steel, Medium': {
    family: 'Plates',
    name: 'Plates of Common Steel, Medium',
    surface: 22,
    cut: 18,
    chop: 12,
    pierce: 20,
    thrust: 16,
    impact: 10,
    flanged: 9,
    weight_per_position: 1.40
  },
  'Plates of Greater Steel, Medium': {
    family: 'Plates',
    name: 'Plates of Greater Steel, Medium',
    surface: 27,
    cut: 22,
    chop: 14,
    pierce: 24,
    thrust: 19,
    impact: 12,
    flanged: 11,
    weight_per_position: 1.40
  },
  'Plates of Mannish High Steel, Light': {
    family: 'Plates',
    name: 'Plates of Mannish High Steel, Light',
    surface: 30,
    cut: 24,
    chop: 12,
    pierce: 19,
    thrust: 16,
    impact: 11,
    flanged: 9,
    weight_per_position: 1.05
  },
  'Plates of Mannish High Steel, Medium': {
    family: 'Plates',
    name: 'Plates of Mannish High Steel, Medium',
    surface: 31,
    cut: 26,
    chop: 17,
    pierce: 28,
    thrust: 22,
    impact: 15,
    flanged: 12,
    weight_per_position: 1.40
  },
  'Plates of Mannish High Steel, Heavy': {
    family: 'Plates',
    name: 'Plates of Mannish High Steel, Heavy',
    surface: 33,
    cut: 27,
    chop: 22,
    pierce: 38,
    thrust: 30,
    impact: 18,
    flanged: 16,
    weight_per_position: 1.75
  },
  'Plates of Wrought Iron, Medium': {
    family: 'Plates',
    name: 'Plates of Wrought Iron, Medium',
    surface: 13,
    cut: 11,
    chop: 7,
    pierce: 12,
    thrust: 10,
    impact: 6,
    flanged: 5,
    weight_per_position: 1.39
  },
  'Plates of Wrought Iron, Heavy': {
    family: 'Plates',
    name: 'Plates of Wrought Iron, Heavy',
    surface: 14,
    cut: 15,
    chop: 9,
    pierce: 16,
    thrust: 13,
    impact: 8,
    flanged: 7,
    weight_per_position: 1.73
  },
  'Hardened Leather, Medium, Studs': {
    family: 'Heavy Leather',
    name: 'Hardened Leather, Medium, Studs',
    surface: 10,
    cut: 11,
    chop: 6,
    pierce: 9,
    thrust: 7,
    impact: 4,
    flanged: 4,
    weight_per_position: 0.69
  },
  'Hardened Leather, Medium, Rings': {
    family: 'Heavy Leather',
    name: 'Hardened Leather, Medium, Rings',
    surface: 13,
    cut: 12,
    chop: 8,
    pierce: 11,
    thrust: 9,
    impact: 4,
    flanged: 5,
    weight_per_position: 0.75
  },
  'Hardened Leather, Medium, Splints': {
    family: 'Heavy Leather',
    name: 'Hardened Leather, Medium, Splints',
    surface: 15,
    cut: 13,
    chop: 9,
    pierce: 12,
    thrust: 9,
    impact: 8,
    flanged: 6,
    weight_per_position: 0.85
  },
  'Hardened Leather, Medium, Bezaints': {
    family: 'Heavy Leather',
    name: 'Hardened Leather, Medium, Bezaints',
    surface: 20,
    cut: 14,
    chop: 10,
    pierce: 13,
    thrust: 10,
    impact: 7,
    flanged: 6,
    weight_per_position: 0.94
  },
  'Leather, Medium, Rings': {
    family: 'Light Leather',
    name: 'Leather, Medium, Rings',
    surface: 9,
    cut: 8,
    chop: 7,
    pierce: 6,
    thrust: 6,
    impact: 4,
    flanged: 5,
    weight_per_position: 0.43
  },
  'Leather, Medium, Studs': {
    family: 'Light Leather',
    name: 'Leather, Medium, Studs',
    surface: 6,
    cut: 7,
    chop: 5,
    pierce: 4,
    thrust: 4,
    impact: 4,
    flanged: 4,
    weight_per_position: 0.37
  },
  'Leather, Heavy, Bezaints': {
    family: 'Heavy Leather',
    name: 'Leather, Heavy, Bezaints',
    surface: 19,
    cut: 13,
    chop: 12,
    pierce: 11,
    thrust: 10,
    impact: 9,
    flanged: 9,
    weight_per_position: 0.78
  },
  'Leather, Heavy, Rings': {
    family: 'Heavy Leather',
    name: 'Leather, Heavy, Rings',
    surface: 12,
    cut: 11,
    chop: 10,
    pierce: 9,
    thrust: 9,
    impact: 6,
    flanged: 8,
    weight_per_position: 0.59
  },
  'Leather, Heavy, Splints': {
    family: 'Heavy Leather',
    name: 'Leather, Heavy, Splints',
    surface: 14,
    cut: 12,
    chop: 11,
    pierce: 10,
    thrust: 9,
    impact: 10,
    flanged: 9,
    weight_per_position: 0.69
  },
  'Leather, Heavy, Studs': {
    family: 'Heavy Leather',
    name: 'Leather, Heavy, Studs',
    surface: 9,
    cut: 10,
    chop: 8,
    pierce: 7,
    thrust: 7,
    impact: 6,
    flanged: 7,
    weight_per_position: 0.53
  },
  'Padded, Bezaints': {
    family: 'Padded',
    name: 'Padded, Bezaints',
    surface: 21,
    cut: 13,
    chop: 13,
    pierce: 13,
    thrust: 10,
    impact: 12,
    flanged: 11,
    weight_per_position: 0.70
  },
  'Dwarven Quilt': {
    family: 'Cloth',
    name: 'Dwarven Quilt',
    surface: 10,
    cut: 11,
    chop: 11,
    pierce: 12,
    thrust: 9,
    impact: 13,
    flanged: 11,
    weight_per_position: 0.35
  },
  'Dwarven Padded': {
    family: 'Padded',
    name: 'Dwarven Padded',
    surface: 14,
    cut: 14,
    chop: 14,
    pierce: 15,
    thrust: 12,
    impact: 16,
    flanged: 14,
    weight_per_position: 0.52
  },
  'Fine Mail, Dwarven Low Steel': {
    family: 'Light Mail',
    name: 'Fine Mail, Dwarven Low Steel',
    surface: 28,
    cut: 25,
    chop: 15,
    pierce: 27,
    thrust: 19,
    impact: 7,
    flanged: 7,
    weight_per_position: 0.95
  },
  'Brazed Mail of Gnomish Steel, Medium': {
    family: 'Light Mail',
    name: 'Brazed Mail of Gnomish Steel, Medium',
    surface: 30,
    cut: 27,
    chop: 16,
    pierce: 29,
    thrust: 20,
    impact: 8,
    flanged: 8,
    weight_per_position: 1.29
  },
  'Double Mail of Gnomish Steel, Medium': {
    family: 'Light Mail',
    name: 'Double Mail of Gnomish Steel, Medium',
    surface: 30,
    cut: 27,
    chop: 15,
    pierce: 26,
    thrust: 28,
    impact: 8,
    flanged: 7,
    weight_per_position: 1.29
  },
  'Laced Mail of Gnomish Steel, Medium': {
    family: 'Heavy Mail',
    name: 'Laced Mail of Gnomish Steel, Medium',
    surface: 34,
    cut: 28,
    chop: 15,
    pierce: 26,
    thrust: 18,
    impact: 9,
    flanged: 10,
    weight_per_position: 1.29
  },
  'Lames of Gnomish Steel, Medium': {
    family: 'Lames',
    name: 'Lames of Gnomish Steel, Medium',
    surface: 44,
    cut: 34,
    chop: 21,
    pierce: 36,
    thrust: 22,
    impact: 19,
    flanged: 16,
    weight_per_position: 1.68
  },
  'Plates of Gnomish Steel, Medium': {
    family: 'Plates',
    name: 'Plates of Gnomish Steel, Medium',
    surface: 38,
    cut: 31,
    chop: 20,
    pierce: 34,
    thrust: 27,
    impact: 18,
    flanged: 15,
    weight_per_position: 1.39
  },
  'Single Mail of Gnomish Steel, Medium': {
    family: 'Light Mail',
    name: 'Single Mail of Gnomish Steel, Medium',
    surface: 29,
    cut: 25,
    chop: 14,
    pierce: 26,
    thrust: 16,
    impact: 7,
    flanged: 7,
    weight_per_position: 0.99
  },
  'Elven Cloth, Light': {
    family: 'Cloth',
    name: 'Elven Cloth, Light',
    surface: 4,
    cut: 3,
    chop: 2,
    pierce: 3,
    thrust: 2,
    impact: 1,
    flanged: 1,
    weight_per_position: 0.03
  },
  'Elven Cloth, Medium': {
    family: 'Cloth',
    name: 'Elven Cloth, Medium',
    surface: 5,
    cut: 4,
    chop: 3,
    pierce: 4,
    thrust: 3,
    impact: 2,
    flanged: 2,
    weight_per_position: 0.06
  },
  'Elven Cloth, Heavy': {
    family: 'Cloth',
    name: 'Elven Cloth, Heavy',
    surface: 7,
    cut: 6,
    chop: 5,
    pierce: 6,
    thrust: 6,
    impact: 3,
    flanged: 3,
    weight_per_position: 0.18
  },
  'Elven Greater Steel Fine Coat of Scales': {
    family: 'Lames',
    name: 'Elven Greater Steel Fine Coat of Scales',
    surface: 35,
    cut: 23,
    chop: 16,
    pierce: 23,
    thrust: 16,
    impact: 13,
    flanged: 8,
    weight_per_position: 1.53
  },
  'Elven Padded': {
    family: 'Padded',
    name: 'Elven Padded',
    surface: 14,
    cut: 15,
    chop: 13,
    pierce: 15,
    thrust: 10,
    impact: 13,
    flanged: 11,
    weight_per_position: 0.36
  },
  'Elven Quilt': {
    family: 'Cloth',
    name: 'Elven Quilt',
    surface: 10,
    cut: 12,
    chop: 10,
    pierce: 12,
    thrust: 8,
    impact: 10,
    flanged: 9,
    weight_per_position: 0.12
  },
  'Elven Silk': {
    family: 'Cloth',
    name: 'Elven Silk',
    surface: 5,
    cut: 7,
    chop: 5,
    pierce: 7,
    thrust: 6,
    impact: 3,
    flanged: 4,
    weight_per_position: 0.12
  },
  'Fine Mail, Elven Travel Steel': {
    family: 'Light Mail',
    name: 'Fine Mail, Elven Travel Steel',
    surface: 28,
    cut: 25,
    chop: 15,
    pierce: 27,
    thrust: 19,
    impact: 7,
    flanged: 7,
    weight_per_position: 0.95
  },
  'Fine Mail, Mannish Greater Steel': {
    family: 'Light Mail',
    name: 'Fine Mail, Mannish Greater Steel',
    surface: 24,
    cut: 22,
    chop: 13,
    pierce: 23,
    thrust: 17,
    impact: 6,
    flanged: 6,
    weight_per_position: 0.95
  },
  'Lames of Elven Bronze': {
    family: 'Lames',
    name: 'Lames of Elven Bronze',
    surface: 28,
    cut: 22,
    chop: 14,
    pierce: 23,
    thrust: 14,
    impact: 13,
    flanged: 10,
    weight_per_position: 0.95
  }
};